services:
  - type: web
    name: otelkontrol_web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    branch: main
    region: frankfurt
